-- Users table seeds here (Example)

-- stories_seed.sql

INSERT INTO stories (title, body, author_id) VALUES
('Whispers in the Moonlight', 'The moon hung low in the velvet sky, casting a silver glow upon the world below. In the quiet stillness of the night, whispers danced on the breeze, secrets shared only between the stars and the souls that wandered beneath their gaze. It was a moment frozen in time, where the ethereal beauty of the night unfolded its mysteries to those who dared to listen.', 1),
('Chronicles of Enigma', 'In the land of Enigma, where shadows waltzed with light, a prophecy unfolded its ancient tale. A hero, unknown and yet to be revealed, was destined to rise from the ashes of obscurity. As the sun dipped below the horizon, painting the sky in hues of amber and rose, the first chapter of a mystical adventure began.', 2),
('The Whispering Woods', 'Deep within the heart of the Whispering Woods, where the leaves rustled secrets and the air hummed with ancient melodies, a lone traveler ventured forth. The trees stood as silent sentinels, guardians of tales untold, as the wanderer embarked on a journey into the heart of mystery and magic.', 3),
('Serenade of the Celestial Spheres', 'In a realm beyond the reach of mortal eyes, where celestial spheres sang in harmonious serenade, a cosmic ballet unfolded. Stars pirouetted in cosmic dance, weaving tales of creation and wonder. It was a symphony of the cosmos, where galaxies whispered their cosmic lullabies to the dreamers of the universe.', 4),
('Echoes of Eternity', 'In the city of eternal echoes, where time flowed like a river with no end, the past and future coalesced in a dance of perpetual existence. Every step echoed through the cobbled streets, resonating with the footsteps of those who had walked the same path in epochs long past. It was a city where the boundary between yesterday and tomorrow blurred into a seamless tapestry of eternity.', 5),
('Mysteries of Celestial Tides', 'Beneath the cosmic tapestry, where celestial tides ebbed and flowed, an ancient mystery unfolded its enigmatic embrace. The stars whispered secrets to the moon, and the moon, in turn, wove tales into the fabric of the night. As constellations traced their luminous arcs, a cosmic voyage embarked upon the astral currents of the universe.', 6),
('Luminescent Labyrinth', 'Beneath the glow of a thousand luminescent lanterns, a labyrinth unfurled its maze of mysteries. Each twist and turn whispered riddles to the wanderers who dared to navigate its corridors. It was a labyrinth of illusions and enlightenment, where the boundaries between reality and fantasy blurred like the edges of a dream.', 7),
('Ephemeral Enchantment', 'In a realm where enchantment painted the air in hues of ephemeral splendor, a sorceress wove spells with threads of moonlight. Her incantations echoed through the valleys, turning every breath into a dance of enchantment. It was a world where the boundary between the tangible and the intangible melted away like morning mist.', 8),
('Symphony of Shadows', 'In the kingdom of perpetual twilight, where shadows danced with the echoes of forgotten tales, a symphony of shadows unfolded its haunting melody. The nocturnal minuet whispered through the corridors of forgotten castles, resonating with the footsteps of phantoms and the murmurs of ancient secrets.', 9),
('Gossamer Dreams', 'Beneath the tapestry of gossamer dreams, where reality and reverie entwined, a dreamweaver spun tales of whimsy and wonder. Each delicate thread shimmered with the essence of imagination, forming a canvas of dreams that stretched beyond the boundaries of the night sky.', 10);
