-- Users table seeds here (Example)
INSERT INTO contributions (body, author_id, story_id) VALUES
('Humility is the practice of recognizing our limitations and imperfections, and it is essential to personal growth and development. Whether it is acknowledging our mistakes and shortcomings, seeking feedback from others, or approaching new situations with a sense of openness and curiosity, humility can help us learn and grow in meaningful ways.', 1, 1),
('Debbie put her hand into the hole, sliding her hand down as far as her arm could reach. She wiggled her fingers hoping to touch something, but all she felt was air. She shifted the weight of her body to try and reach an inch or two more down the hole. Her fingers still touched nothing but air.', 1, 1),
('They argue. While the argument seems to be different the truth is it is always the same. Yes, the topic may be different or the circumstances, but when all said and done, it all came back to the same thing. They both knew it, but neither has the courage or strength to address the underlying issue. So they continue to argue.', 1, 1),
('She had been told time and time again that the most important steps were the first and the last. It was something that she carried within her in everything she did, but then he showed up and disrupted everything. He told her that she had it wrong. The first step was not the most important. The last step was not the most important. It was the next step that was the most important.', 1, 1),
('There once lived an old man and an old woman who were peasants and had to work hard to earn their daily bread. The old man used to go to fix fences and do other odd jobs for the farmers around, and while he was gone the old woman, his wife, did the work of the house and worked in their own little plot of land.', 2, 2),
('She wanted rainbow hair. That is what she told the hairdresser. It should be deep rainbow colors, too. She was not interested in pastel rainbow hair. She wanted it deep and vibrant so there was no doubt that she had done this on purpose.', 2, 2),
('The boy walked down the street in a carefree way, playing without notice of what was about him. He did not hear the sound of the car as his ball careened into the road. He took a step toward it, and in doing so sealed his fate.', 2, 2),
('He sat across from her trying to imagine it was the first time. It was not. Had it been a hundred? It quite possibly could have been. Two hundred? Probably not. His mind wandered until he caught himself and again tried to imagine it was the first time.', 3, 3),
('He wondered if he should disclose the truth to his friends. It would be a risky move. Yes, the truth would make things a lot easier if they all stayed on the same page, but the truth might fracture the group leaving everything in even more of a mess than it was not telling the truth. It was time to decide which way to go.', 3, 3),
('She considered the birds to be her friends. She would put out food for them each morning and then she would watch as they came to the feeders to gorge themselves for the day. She wondered what they would do if something ever happened to her. Would they miss the meals she provided if she failed to put out the food one morning?', 4, 4);
